spring:
  data:
    mongodb:
      username: series_databse
      password: series
      database: series
      port: 27018
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

queue:
  serie:
    name: SerieQueue

server:
  port: 9002

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: loclahost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: movie microservice
  svc:
    instanceid: ${eureka.instance.instancei-id}
    port: ${server.port}